backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "contact"
    label: "Contact Info"
    file: "content/contact.md"
    fields:
      - { label: "Address", name: "address", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Phone", name: "phone", widget: "string" }

  - name: "programs"
    label: "Programs"
    folder: "content/programs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Program Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }

  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Caption", name: "caption", widget: "string" }